version: "3"
services:
  server:
    container_name: server
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm run prod